apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app.kubernetes.io/name: kafka
spec:
  ports:
    - name: kafka
      port: 9092
  selector:
    app.kubernetes.io/name: kafka
  type: NodePort

