apiVersion: v1
kind: Pod
metadata:
  name: producer-v1
spec:
  containers:
  - name: health-check-v6
    image: sumanthksai/producer-v1:latest
    envFrom:
        - configMapRef:
            name: health-check-config
